//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lit", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin panel.
        /// </summary>
        internal static string adminpanel {
            get {
                return ResourceManager.GetString("adminpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        internal static string bando {
            get {
                return ResourceManager.GetString("bando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        internal static string bd {
            get {
                return ResourceManager.GetString("bd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ hiển thị.
        /// </summary>
        internal static string bohienthi {
            get {
                return ResourceManager.GetString("bohienthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOO.
        /// </summary>
        internal static string BOO {
            get {
                return ResourceManager.GetString("BOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần Giờ.
        /// </summary>
        internal static string cangio {
            get {
                return ResourceManager.GetString("cangio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình logger.
        /// </summary>
        internal static string cauhinhlogger {
            get {
                return ResourceManager.GetString("cauhinhlogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chợ Lớn.
        /// </summary>
        internal static string cholon {
            get {
                return ResourceManager.GetString("cholon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm lắp đặt.
        /// </summary>
        internal static string diemlapdat {
            get {
                return ResourceManager.GetString("diemlapdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm lắp đặt xí nghiệp quản lý.
        /// </summary>
        internal static string diemlapdatxinghiepquanly {
            get {
                return ResourceManager.GetString("diemlapdatxinghiepquanly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string doimatkhau {
            get {
                return ResourceManager.GetString("doimatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng hồ.
        /// </summary>
        internal static string dongho {
            get {
                return ResourceManager.GetString("dongho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng hồ đến hạn kiểm định.
        /// </summary>
        internal static string donghodenhankiemdinh {
            get {
                return ResourceManager.GetString("donghodenhankiemdinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị.
        /// </summary>
        internal static string dothi {
            get {
                return ResourceManager.GetString("dothi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị 2 nhóm lắp đặt.
        /// </summary>
        internal static string dothi2nhomlapdat {
            get {
                return ResourceManager.GetString("dothi2nhomlapdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị một công ty CP.
        /// </summary>
        internal static string dothimotcongty {
            get {
                return ResourceManager.GetString("dothimotcongty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị một điểm lắp đặt.
        /// </summary>
        internal static string dothimotdiemlapdat {
            get {
                return ResourceManager.GetString("dothimotdiemlapdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị công ty CP và nhóm.
        /// </summary>
        internal static string dothitheocongtyvanhom {
            get {
                return ResourceManager.GetString("dothitheocongtyvanhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị công ty CP và nhóm 2.
        /// </summary>
        internal static string dothitheocongtyvanhom2 {
            get {
                return ResourceManager.GetString("dothitheocongtyvanhom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị theo điểm lắp đặt và công ty CP.
        /// </summary>
        internal static string dothitheodiemlapdatvacongty {
            get {
                return ResourceManager.GetString("dothitheodiemlapdatvacongty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị theo điểm lắp đặt và nhóm 1.
        /// </summary>
        internal static string dothitheodiemlapdatvanhom1 {
            get {
                return ResourceManager.GetString("dothitheodiemlapdatvanhom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị theo điểm lắp đặt và nhóm 2.
        /// </summary>
        internal static string dothitheodiemlapdatvanhom2 {
            get {
                return ResourceManager.GetString("dothitheodiemlapdatvanhom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị theo nhóm đồng hồ 1.
        /// </summary>
        internal static string dothitheonhomdongho1 {
            get {
                return ResourceManager.GetString("dothitheonhomdongho1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị theo nhóm đồng hồ 2.
        /// </summary>
        internal static string dothitheonhomdongho2 {
            get {
                return ResourceManager.GetString("dothitheonhomdongho2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file điểm lắp đặt.
        /// </summary>
        internal static string downloadfilediemlapdat {
            get {
                return ResourceManager.GetString("downloadfilediemlapdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file đồng hồ.
        /// </summary>
        internal static string downloadfiledongho {
            get {
                return ResourceManager.GetString("downloadfiledongho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồ thị.
        /// </summary>
        internal static string dt {
            get {
                return ResourceManager.GetString("dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia Định.
        /// </summary>
        internal static string giadinh {
            get {
                return ResourceManager.GetString("giadinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HM.
        /// </summary>
        internal static string hm {
            get {
                return ResourceManager.GetString("hm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        internal static string hoatdong {
            get {
                return ResourceManager.GetString("hoatdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động phát sinh trong kỳ.
        /// </summary>
        internal static string hoatdongphatsinh {
            get {
                return ResourceManager.GetString("hoatdongphatsinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ thiết bị.
        /// </summary>
        internal static string hosothietbi {
            get {
                return ResourceManager.GetString("hosothietbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ thiết bị bộ hiển thị.
        /// </summary>
        internal static string hosothietbibohienthi {
            get {
                return ResourceManager.GetString("hosothietbibohienthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ thiết bị đồng hồ.
        /// </summary>
        internal static string hosothietbidongho {
            get {
                return ResourceManager.GetString("hosothietbidongho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ thiết bị logger.
        /// </summary>
        internal static string hosothietbilogger {
            get {
                return ResourceManager.GetString("hosothietbilogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử điểm lắp đặt.
        /// </summary>
        internal static string lichsudiemlapdat {
            get {
                return ResourceManager.GetString("lichsudiemlapdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger.
        /// </summary>
        internal static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu in.
        /// </summary>
        internal static string mauin {
            get {
                return ResourceManager.GetString("mauin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nắp hầm.
        /// </summary>
        internal static string napham {
            get {
                return ResourceManager.GetString("napham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string ngonngu {
            get {
                return ResourceManager.GetString("ngonngu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà Bè.
        /// </summary>
        internal static string nhabe {
            get {
                return ResourceManager.GetString("nhabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập liệu.
        /// </summary>
        internal static string nhaplieu {
            get {
                return ResourceManager.GetString("nhaplieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tay chỉ số.
        /// </summary>
        internal static string nhaptaychiso {
            get {
                return ResourceManager.GetString("nhaptaychiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tay sản lượng.
        /// </summary>
        internal static string nhaptaysanluong {
            get {
                return ResourceManager.GetString("nhaptaysanluong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phú Hòa Tân.
        /// </summary>
        internal static string phuhoatan {
            get {
                return ResourceManager.GetString("phuhoatan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sài Gòn.
        /// </summary>
        internal static string saigon {
            get {
                return ResourceManager.GetString("saigon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng.
        /// </summary>
        internal static string sanluong {
            get {
                return ResourceManager.GetString("sanluong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng các công ty cấp nước.
        /// </summary>
        internal static string sanluongcaccongtycapnuoc {
            get {
                return ResourceManager.GetString("sanluongcaccongtycapnuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng theo cấp đồng hồ.
        /// </summary>
        internal static string sanluongtheocapdongho {
            get {
                return ResourceManager.GetString("sanluongtheocapdongho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng theo nhóm.
        /// </summary>
        internal static string sanluongtheonhom {
            get {
                return ResourceManager.GetString("sanluongtheonhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng theo nhóm 2.
        /// </summary>
        internal static string sanluongtheonhom2 {
            get {
                return ResourceManager.GetString("sanluongtheonhom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng theo quản lý.
        /// </summary>
        internal static string sanluongtheoquanly {
            get {
                return ResourceManager.GetString("sanluongtheoquanly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng tổng hợp.
        /// </summary>
        internal static string sanluongtonghop {
            get {
                return ResourceManager.GetString("sanluongtonghop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng.
        /// </summary>
        internal static string sl {
            get {
                return ResourceManager.GetString("sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa dữ liệu.
        /// </summary>
        internal static string suadulieu {
            get {
                return ResourceManager.GetString("suadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string taikhoan {
            get {
                return ResourceManager.GetString("taikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tân Hòa.
        /// </summary>
        internal static string tanhoa {
            get {
                return ResourceManager.GetString("tanhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới dữ liệu khác.
        /// </summary>
        internal static string taomoidulieukhac {
            get {
                return ResourceManager.GetString("taomoidulieukhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới người dùng.
        /// </summary>
        internal static string taomoinguoidung {
            get {
                return ResourceManager.GetString("taomoinguoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay bộ hiển thị.
        /// </summary>
        internal static string thaybohienthi {
            get {
                return ResourceManager.GetString("thaybohienthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đồng hồ.
        /// </summary>
        internal static string thaydongho {
            get {
                return ResourceManager.GetString("thaydongho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay logger.
        /// </summary>
        internal static string thaylogger {
            get {
                return ResourceManager.GetString("thaylogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo hiệu cỡ (xí nghiệp quản lý).
        /// </summary>
        internal static string theohieuco {
            get {
                return ResourceManager.GetString("theohieuco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị.
        /// </summary>
        internal static string thietbi {
            get {
                return ResourceManager.GetString("thietbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian đồng hồ hoạt động.
        /// </summary>
        internal static string thoigiandonghohoatdong {
            get {
                return ResourceManager.GetString("thoigiandonghohoatdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        internal static string thongke {
            get {
                return ResourceManager.GetString("thongke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê tùy chọn bộ hiển thị.
        /// </summary>
        internal static string thongketuychonbohienthi {
            get {
                return ResourceManager.GetString("thongketuychonbohienthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê tùy chọn điểm lắp đặt.
        /// </summary>
        internal static string thongketuychondiemlapdat {
            get {
                return ResourceManager.GetString("thongketuychondiemlapdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê tùy chọn đồng hồ.
        /// </summary>
        internal static string thongketuychondongho {
            get {
                return ResourceManager.GetString("thongketuychondongho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê tùy chọn hiệu cỡ.
        /// </summary>
        internal static string thongketuychonhieuco {
            get {
                return ResourceManager.GetString("thongketuychonhieuco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê tùy chọn logger.
        /// </summary>
        internal static string thongketuychonlogger {
            get {
                return ResourceManager.GetString("thongketuychonlogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin điểm lắp đặt.
        /// </summary>
        internal static string thongtindiemlapdat {
            get {
                return ResourceManager.GetString("thongtindiemlapdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ Đức.
        /// </summary>
        internal static string thuduc {
            get {
                return ResourceManager.GetString("thuduc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string tienganh {
            get {
                return ResourceManager.GetString("tienganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string tiengviet {
            get {
                return ResourceManager.GetString("tiengviet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện ích.
        /// </summary>
        internal static string tienich {
            get {
                return ResourceManager.GetString("tienich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string tk {
            get {
                return ResourceManager.GetString("tk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trung An.
        /// </summary>
        internal static string trungan {
            get {
                return ResourceManager.GetString("trungan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem người dùng.
        /// </summary>
        internal static string xemnguoidung {
            get {
                return ResourceManager.GetString("xemnguoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bộ hiển thị không sử dụng.
        /// </summary>
        internal static string xoabohienthi {
            get {
                return ResourceManager.GetString("xoabohienthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa đồng hồ không sử dụng.
        /// </summary>
        internal static string xoadongho {
            get {
                return ResourceManager.GetString("xoadongho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa logger không sử dụng.
        /// </summary>
        internal static string xoalogger {
            get {
                return ResourceManager.GetString("xoalogger", resourceCulture);
            }
        }
    }
}
